// import type { Metadata } from "next";
'use client'

import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Provider } from 'react-redux';
import { store } from '@/redux/store'; // Import store từ store.ts


import * as api from '@/utils/api'
import { useEffect } from "react";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <Provider store={store}>
    <html lang="en"  style={{height :'100%'}} >
      <body style={{height :'100%'}} className={inter.className}>{children}</body>
    </html>
    </Provider>
  );
}
